name: Continuous Integration

on:
    push:
        branches:
            - main
        tags:
            - "!*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "7.0.100-rc.1.22431.12"
            - name: Build .NET app
              run: dotnet build
            - name: Test .NET app
              run: dotnet test
